# Generated by Django 3.2 on 2021-04-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miaimmagine',
            old_name='Main_Img',
            new_name='Immagine',
        ),
        migrations.RenameField(
            model_name='miaimmagine',
            old_name='name',
            new_name='Nome',
        ),
    ]
