# Generated by Django 3.2 on 2021-04-21 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Genio', '0002_auto_20210419_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='miaimmagine',
            name='Image_Width',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
