# Generated by Django 3.2 on 2021-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genio', '0004_auto_20210421_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miaimmagine',
            name='Image_DPI_Height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
