# Generated by Django 3.2 on 2021-04-22 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Genio', '0005_alter_miaimmagine_image_dpi_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miaimmagine',
            name='Image_DPI_Height',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
